# ПЕРЕМЕННЫЕ

name: Eleven Workflow
on: push
env:
  WF_CUSTOM_VAR: WF 1 # задавать переменныйе с большой буквы
jobs:
  run-first-command:
    runs-on: ubuntu-latest
    env:
      JOB_CUSTOM_VAR: JOB 1
    steps:
      - name: Set New Var
        run: echo "NEW_WAR=New Value" >> "$GITHUB_ENV"
      - name: Event Vars
        env:
          STEP_CUSTOM_VAR: STEP 1
          WF_CUSTOM_VAR: WF 1 - STEP 2
        run: |
          echo $GITHUB_REF
          echo '${{ github.ref }}'
          echo $WF_CUSTOM_VAR
          echo $JOB_CUSTOM_VAR
          echo $STEP_CUSTOM_VAR
          echo '${{ env.WF_CUSTOM_VAR }}'
          echo $NEW_WAR

# echo $WF_CUSTOM_VAR  #генирируется на стороне локальной машины, ранер достает значение
# $WF_CUSTOM_VAR имеет смысл только при работе с шагом

# echo '${{ env.WF_CUSTOM_VAR }'  # генерируется на стороне гитхаба, уже имеет готовое значение

# "$GITHUB_ENV" - путь до особого файла со всеми переменными
