name: Fifth Workflow
on: 
  issues:
    types: [edited, deleted]
  pull_request:
    types: [assigned, closed]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display some Text
        run: echo "Some Text"
      - name: Event Vars
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF