name: Firs Workflow
on: [push]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display some text
        run: echo "Some Text"
      - name: command in Multititle
        run: |
          node -v
          npm -v

