name: Second Workflow
on: push

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display some text U
        run: 
          node -v
  run-parallel-command:
    runs-on: windows-latest
    steps:
      - name: Display some text W
        run: 
          node -v
  run-second-command:
    runs-on: macos-latest
    needs: run-first-command
    steps:
      - name: Display some text M
        run: 
          node -v


        

